### ISSUE TITLE
It's not clear that bubblewrap v0.7.0 should be used 

### ISSUE THREAD

**Issue by Kleidukos** [haskell/play-haskell#19]
When following the installation procedure I get on Fedora 37:

`bwrap: Unknown option --size` 

This is because Fedora 37 has bubblewrap has a foundational dependency for other tools, and the distributed version is `0.5.0`.

Bubblewrap 0.7.0 can be installed manually but the documentation should be amended

**Comment by tomsmeding** [comment]
> Bubblewrap 0.7.0 can be installed manually but the documentation should be amended

Fair point. I think this is indeed purely a documentation bug -- bwrap 0.7.0 is the first version to have the `--size` option, which we need here. Installing manually is not that difficult but it should indeed be mentioned in the readme.

**Comment by tomsmeding** [comment]
Sorry for the delay!
