### ISSUE TITLE
Example inefficient?

### ISSUE THREAD

**Issue by turion** [haskell/play-haskell#23]
https://github.com/haskell/play-haskell/blob/c0341e70b083961b7ecb0aa7e051e620a3e16135/play-haskell-server/static/play-index.ts#L42

Shouldn't this be:

```haskell
toright (x:xs) = second (x :) (toleft xs)
```
Otherwise the lists aren't split into evenly sized parts, which I guess is only O(n^2) and not O(n log n).

**Comment by tomsmeding** [comment]
Uh, oops :) What do you think of this improvement? As a side-effect this actually also removes the need for the Bifunctor import. https://play.haskell.org/saved/j4vMomi2

**Comment by turion** [comment]
> What do you think of this improvement? As a side-effect this actually also removes the need for the Bifunctor import.

Yes, that's a great improvement!

> The quicksort example is actually also O(n^2)

I guess it's only O(n^2) worst case? Which is fine I think. Selecting a clever pivot (median guess or whatever) would obfuscate it.
