### ISSUE TITLE
Add Yampa, dunai to packages available

### ISSUE THREAD

**Issue by ivanperez-keera** [haskell/play-haskell#27]
### Feature request

I'd like to propose adding Yampa and dunai to the list of packages available.

They are both reactive programming implementations (built on related but different abstractions). They are both well maintained (both released every 2 months). Yampa has been around for more than 20 years now.

Having them available in play-haskell would make it easier for people to learn the concepts that these libraries are built on.

**Comment by tomsmeding** [comment]
Resolved after merging #28
