### ISSUE TITLE
Add `ghc-internal` to the list of visible packages

### ISSUE THREAD

**Issue by s-and-witch** [haskell/play-haskell#45]
### Feature request

If you try to import any module from `ghc-internal` (e.g. `GHC.Internal.TypeError`), that was introduced in ghc 9.10, you get this error:
```
Main.hs:2:1: error: [GHC-87110]
    Could not load module ‘GHC.Internal.TypeError’.
    It is a member of the hidden package ‘ghc-internal-9.1001.0’.
    Use -v to see a list of the files searched for.
```

That limits access to the newly introduced Haskell features, so the user can't test to see some corner cases of the behavior or present a showcase to others about how useful the feature is.

**Comment by tomsmeding** [comment]
Thanks, apparently I haven't been following stuff closely enough! Looking at the GHC 9.10 changelog (which doesn't mention `ghc-internal`!), I guess that also goes for `ghc-experimental` and `ghc-heap`?

**Comment by s-and-witch** [comment]
That's true for `ghc-experimental`, i.e. I can't import `Data.Tuple.Experimental`, but I can import modules from `ghc-heap`

**Comment by tomsmeding** [comment]
Fixed in https://github.com/haskell/play-haskell/commit/7eeb82a017a5f78c1d380fde1c08bf8dbf508d27
